# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.


local:
  secret_key_base: baf529cb9e28da8ba2b517ab61846e0f2caea7a6d0c29144f89364e522d4bd7b7ff488d2bcc308a1b5eebfb597db1f13eed003194a571bfb066100fceb3bfbe5


development:
  secret_key_base: baf529cb9e28da8ba2b517ab61846e0f2caea7a6d0c29144f89364e522d4bd7b7ff488d2bcc308a1b5eebfb597db1f13eed003194a571bfb066100fceb3bfbe5

test:
  secret_key_base: 22e110f3c0ee0d6e147576c9de2a1851d141582e78b48abeac44ea5b41862eb7b1bcea4e340d2dae3c9631c24d3abb32a9a84e6bbbc72606ebf0a8b53b8e0fa2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
#  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: 339a284cc1c203ba25cd52e64b49de6c01910462f8c623c4a701db4f81a5cad1af75e40cddf3d3003f84a0259766c4bc2d68246df1000c907849ef4e90349f92
